### PR TITLE
add cspell to yarn, and fix all obvious spelling errors.

### PR DESCRIPTION
**Pull request by tocklime**
This is WIP - there's still errors in 0.6.0 and top level README.md. Also some tidying up to be done (move local dictionary into its own file, rather than inlined in cspell.json), but wanted to get this PR open in case I've got anything super wrong.

I've added `yarn spellcheck`, which invokes cspell on all .md files (except those under a /vendor/ directory).

### CODE REVIEW

**Comment by tocklime** [comment]
Ok, this is ready to look at. you can run `yarn spellcheck` to run cspell, but I've not integrated the spell check into the github flow or anything.

**Comment by MartinKavik** [comment]
- [ ] Do you know a Rust alternative for `cspell`? If no, create a new issue please, we should use only Rust libraries if possible. On the first attempt I found only https://crates.io/crates/spellbound as a cross-platform low-level building block for future CLI tool. And I'd rather not add any binding libraries because they often don't work on Windows.
- [ ] File `cspell.json` should be in `/configs` folder (?) or in a new folder together with `words.txt` (?)
- [ ] `words.txt` - could we rename it to something like `ignored_cspell_words.json`?
- [ ] I think `cspell` should be moved from `dependencies` into `devDependencies` in `package.json`.
- [ ] Spellcheck should be a part of the task `cargo make verify`. Please resolve it or create a new issue and we'll configure it later.
- [ ] Change `"cspell": "^4.0.63"` to `"cspell": "4.0.63"` (?). We've got multiple deps problems so we try to define versions in a more strict way.

Thanks for the PR and fixes good job!

**Comment by tocklime** [comment]
I don't know of a rust only spell checker. Found https://crates.io/crates/cargo-spellcheck, but it seems to rely on installed libs on linux and mac, so i think is more likely to not compile than the node/js cspell.

The rest of the suggestions seem good. I'll move the 2 files together in their own directory, but words.txt should stay as something.txt, as it's a text file (newline separated words) not json..

**Comment by MartinKavik** [comment]
> words.txt should stay as something.txt, as it's a text file (newline separated words) not json..

My favorite recent hobby is to write typos.. yeah, I meant `txt`.

> Found https://crates.io/crates/cargo-spellcheck

I also didn't find something usable, so let's use your `cspell`.

**Comment by tocklime** [comment]
I'm expecting this to fail with spelling errors - testing that the flow is actually doing it.

**Comment by tocklime** [comment]
...damn

**Comment by MartinKavik** [comment]
> Also, I couldn't figure out how to invoke cspell or yarn from within cargo-make, so I'm doing it by adding an extra step in .github/workflows/main.

Spellcheck has to be run as a part of `cargo make verify` so you can run it before push. Please don't add extra step into CI workflow. I think we can merge it without it and I'll try to resolve it in a new PR - let me know once PR is ready to merge.

**Comment by MartinKavik** [comment]
> I think that something is interpreting the ./**/*.md too early

Current code:
```js
"spellcheck": "yarn cspell --config configs/cspell.json ./\\*\\*/\\*.md"
```

I don't know `cspell` but according to docs (https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell#usage) I would try something like:
```js
"spellcheck": "yarn cspell --config configs/cspell.json \"crate/guides/**/*.md\""
```
Also I'm not sure that `./` would work in Windows terminal.

**Comment by tocklime** [comment]
From github actions:
```
+ yarn spellcheck
yarn run v1.22.4
$ yarn cspell --config configs/cspell.json "**/*.md"
$ /home/runner/work/seed-rs.org/seed-rs.org/node_modules/.bin/cspell --config configs/cspell.json '**/*.md'
CSpell: Files checked: 47, Issues found: 0 in 0 files
Done in 5.43s.
```

Looks like it's doing the spell check correctly now, as part of cargo make verify

**Pull request merged**
