### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by d2weber**

### CODE REVIEW

**Comment by MartinKavik** [comment]
Thanks for the PR!
Please fix the clippy errors and I'll merge it. (Clippy errors are caused by a new Rust version)

**Comment by MartinKavik** [comment]
Note: You can lint the code (simulate CI pipeline) by running `cargo make verify` in the `crate` folder (if I remember the command correctly). You only need the latest stable Rust.

**Comment by d2weber** [comment]
> Note: You can lint the code (simulate CI pipeline) by running `cargo make verify` in the `crate` folder (if I remember the command correctly). You only need the latest stable Rust.

Yes thank you. Currently I'm on the phone because I hoped to make the change to the docs without compiling locally, but.. apearantly I would be faster compiling (or verifying) lokally. I will do it hopefully this evening.

By the way, I really like the ideas of seed and what I've seen so far looks very promising. Thank you for that awesome project.

**Comment by MartinKavik** [comment]
Tests passed, merging, thanks!

> By the way, I really like the ideas of seed and what I've seen so far looks very promising. Thank you for that awesome project.

Thank you! Btw I work also on another framework: [moonzoon.rs](http://moonzoon.rs/)

**Comment by d2weber** [comment]
I will definitely have look at moonzoon.

**Pull request merged**
