### PR TITLE
position fixed sidebar, but it's all a huge hack

### PR DESCRIPTION
**Pull request by sabine**
Still, this is hopefully more readable than before

### CODE REVIEW

**Comment by MartinKavik** [comment]
image
vs old
image

Layout is broken also on mobile. I cannot merge it, it doesn't have to be nice but it shouldn't look broken.

**Comment by sabine** [comment]
I changed the sidebar to be 300px wide and be in a `.container` together with the main content. Does that work?

What is wrong on mobile? The same thing is probably still broken, but I need to know what the problem is. When I make the window really small on a desktop browser, it seems to be okay in my browsers.

**Comment by MartinKavik** [comment]
Good job! The layout with wider menu is better than the original one and the removed border looks like a good improvement 👍 

The last small issue: Missing margin above the big Seed logo:
image
vs old
image

---

Then, please:
1. Remove commented code (e.g. `//C.w_full`)
2. Rebase on the current `master` (I've deactivated Firefox testing due to the broken driver - without it the CI pipeline fails)
3. Run `cargo make verify` in your terminal in `/crate` to make sure the code is formatted and Clippy is happy (without it the CI fails)

Thank you!

---

And how it looks now on Windows + Firefox:
image

**Comment by sabine** [comment]
I added a margin-top to the big seed logo. Seems to be ok now, even on the small screen.

I can't seem to run the tests, though, I tried both on my fork and on the current seed-rs.org master.

```
     Running target/wasm32-unknown-unknown/debug/deps/test-30ae41c37d63a982.wasm
Set timeout to 20 seconds...
Running headless tests in Firefox on `http://127.0.0.1:46435/`
Try find `webdriver.json` for configure browser's capabilities:
Not found
driver status: signal: 9                          
driver stdout:
    1597578541725	geckodriver	INFO	Listening on 127.0.0.1:46435

Error: non-200 response code: 500                 
{"value":{"error":"unknown error","message":"Invalid Content-Type","stacktrace":""}}
error: test failed, to rerun pass '--test test'
Error: Running Wasm tests with wasm-bindgen-test failed
```

**Comment by MartinKavik** [comment]
It's Firefox driver problem - see https://github.com/seed-rs/seed/commit/fe9bd9cb93824c8936a4601c728fe8df2eb4a09a and the related issue in the the code. Just deactivate Firefox tests the same way, please.

**Comment by MartinKavik** [comment]
Merging, I'll fix issues in the next PR.

**Pull request merged**
