### PR TITLE
Fixes #36

### LINKED ISSUE #36: About page issues
Front page under "note on view syntax" it says
`The lack of resemblance to HTML be offputting,`
I think this should read
`The lack of resemblance to HTML may be offputting,`
Also the "why add another?" section
`it uses Rust builtin types, with thinly-wrapped by macros`
makes more sense without the "with"
`it uses Rust builtin types, thinly wrapped by macros`

- `Yasmi` (chat, `documentation` channel)

### PR DESCRIPTION
**Pull request by iahmed5**

### CODE REVIEW

**Comment by MartinKavik** [comment]
Why closed?

**Comment by iahmed5** [comment]
> Why closed?

PR failed some checks so just did it again.

**Comment by MartinKavik** [comment]
Some tips:
- Please use a more descriptive PR name and then you can write `Fixes #XX` in the description.
- You don't have to close PRs - just push/force push the same branch and PRs will be automatically refreshed.
- Make sure you have the latest Rust (`rustup update`) and then run `cargo make verify` in `crate` directory to make sure that all tests pass - the same tests and linters are executed on the CI pipeline.

Thanks for fixes!

**Comment by iahmed5** [comment]
> Some tips:
> 
> * Please use a more descriptive PR name and then you can write `Fixes #XX` in the description.
> * You don't have to close PRs - just push/force push the same branch and PRs will be automatically refreshed.
> * Make sure you have the latest Rust (`rustup update`) and then run `cargo make verify` in `crate` directory to make sure that all tests pass - the same tests and linters are executed on the CI pipeline.
> 
> Thanks for fixes!

Understood. Just a question about `cargo make verify` its seems to be invalid command as the terminal throws the following error.

image

I have tried `cargo check` command mentioned in [Rust doc](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/cargo-check-for-faster-checking.html) instead on my clone without making any changes and it returns the following error.

image

...
`rust update`
image

Is there something I am doing wrong?

**Comment by MartinKavik** [comment]
This repo is based on this template - https://github.com/seed-rs/seed-quickstart-webpack. There should be everything that you need to resolve problems above in the README. 

Basically you need to install `cargo make` (`cargo install cargo-make`) and classes are generated by Webpack so you need to run at least `yarn generate:css_classes` (https://github.com/seed-rs/seed-quickstart-webpack/blob/master/package.json#L10).

**Pull request closed without merging**
