### PR TITLE
Add a chapter for explaining Seed features

### PR DESCRIPTION
**Pull request by arn-the-long-beard**
Hey guys,

As discussed on discord, it could be nice to add some tutorial/documentation on **seed-rs.org** to explain major concepts such as `Orders::subscribe` & `Orders::notify` but maybe `routing` and other topics as well.

Since it is a chapter a bit different from just an app, I added it at the very end on the menu.

I think we need to : 

- [ ] Discuss and find out which concepts to present there.
- [ ] Make some tiny app or code for each of them maybe .
- [ ] Write the .md file for each of them.

### CODE REVIEW

**Comment by arn-the-long-beard** [comment]
Hello !

Thank you so much for your post.

> Also we have a bad experience with too small examples that demonstrate concepts for large apps - especially introduced boilerplate by Elm architecture modules in a small example was/is "very popular" among the example code readers. It provoked many comments about how bad TEA is. Another popular "topic" is routing - it looks very cumbersome in a small example and people try to improve the API. Until they try to design better API that is usable in larger apps with nested pages.

I do agree on that and I understand that you want consistency regarding the flow.

I will come tomorrow with new propositions :smile:

**Comment by arn-the-long-beard** [comment]
Okay, Then I think I should start small. There are a lot about notify & subscribe in https://seed-rs.org/0.7.0/todomvc_routing/

I will do as you suggest and make page there.

> A chapter about notify/subscribe after https://seed-rs.org/0.7.0/todomvc_routing or after Time Tracker authorization (I haven't written it yet.)

Did you mean page right ? Because I am not sure what to put if I have to write an entire chapter there.

**Comment by MartinKavik** [comment]
Yeah, a page. I call them chapters instead of pages because they are often pretty long and once we decide to export them to something like a pdf file so users can read it offline, then each chapter will have many pages.

**Comment by arn-the-long-beard** [comment]
Ok thank you for your message :D 

I do some stuff for **hooks** right now and then I go back with new proposition :)

**Comment by arn-the-long-beard** [comment]
Hello :) 

I have been a bit busy on other parts related to seed, especially the atomic_hook and there is more work there to be done if we want to integrate it to Seed to work on performances.

I think I might not be able to commit on tutorials for seed-rs.org as I wanted in the first place.

Is it fine if somebody continue this PR ? Or should we close it ?

**Comment by MartinKavik** [comment]
Closing. I'm also focusing on other things now so I wouldn't be able to do proper reviews / give feedback.

**Comment by arn-the-long-beard** [comment]
Ok :smile: 

Thank you for your message!

**Pull request closed without merging**
