### PR TITLE
Do not show blue panel while loading

### PR DESCRIPTION
**Pull request by akhilman**
Delay appearance of the warning message with CSS animation to avoid blinking.

Solves #53

### CODE REVIEW

**Comment by MartinKavik** [comment]
_"This is a pre rendered page. Please make sure your have a browser with WebAssembly support  and JavaScript enabled to get all page functionality."_
 - What if your internet connection is slow? A think there is missing something like `Loading...`.
 - Is information  _"This is a pre rendered page."_ valuable for users?
 - It should be "floating above" the website to prevent content jumping once the panel is hidden.
 - What problem are we resolving with this solution? I expect that our target audience - developers - has the latest browser and JS enabled.

**Comment by akhilman** [comment]
>     * What if your internet connection is slow? A think there is missing something like `Loading...`.
The "Loading..." message will also be misleading if the javascript is disabled.

>     * Is information  _"This is a pre rendered page."_ valuable for users?
May be not. Is there a clearer wording?

>     * It should be "floating above" the website to prevent content jumping once the panel is hidden.
A floating message should have a close button and can become even more annoying. If a static page is displayed, this message will appear again when clicking on the link. 
We do not have JavaScript to save the state of the message.

>     * What problem are we resolving with this solution? I expect that our target audience - developers - has the latest browser and JS enabled.

My friend opened seed-rs.org in the SeaMonkey browser, this browser does not support WebAssembly. He complained that the button for changing the dark / light mode does not work, and also the search field does not respond to the entered text.

The main goal is to inform the user about the reasons for the page not working correctly.

**Comment by akhilman** [comment]
Maybe something like this:
"""
Loading... If this message does not disappear for a long time, make sure you have a browser with WebAssembly support and JavaScript enabled.
"""

**Comment by MartinKavik** [comment]
> Loading... If this message does not disappear for a long time, make sure you have a browser with WebAssembly support and JavaScript enabled.

Can be. I'm pretty sure that `Loading..` will be the common case. Imagine phone not connected to Wifi.

**Comment by MartinKavik** [comment]
> A floating message should have a close button and can become even more annoying.

It's fact that it would prevent reading the content. Ok, we'll polish it during the next website redesign.

**Comment by MartinKavik** [comment]
Please squash commits and request review once ready, thanks!

**Comment by MartinKavik** [comment]
Please squash commits and I'll merge it once I'm back home.

**Pull request merged**
